In [10]:
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix,classification_report, accuracy_score

import numpy as np

import matplotlib.pyplot as plt

import pandas as pd

df=pd.read_csv("../data/phishing_email.csv")

df.head()
print(df.describe())
print(df.info())

              label
count  82486.000000
mean       0.519979
std        0.499604
min        0.000000
25%        0.000000
50%        1.000000
75%        1.000000
max        1.000000
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 82486 entries, 0 to 82485
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   text_combined  82486 non-null  object
 1   label          82486 non-null  int64 
dtypes: int64(1), object(1)
memory usage: 1.3+ MB
None


In [11]:
X=df['text_combined']
y=df['label']

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42,stratify=y)


In [12]:
tfidf=TfidfVectorizer()

X_train_tfidf = tfidf.fit_transform(X_train)

X_test_tfidf  = tfidf.transform(X_test)

X_train_tfidf




<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 6761873 stored elements and shape (65988, 553008)>

In [13]:
model=LogisticRegression()

model.fit(X_train_tfidf,y_train)


y_pred=model.predict(X_test_tfidf)


In [14]:
y_pred.reshape(-1,1)


array([[1],
       [0],
       [1],
       ...,
       [1],
       [0],
       [0]], shape=(16498, 1))

In [15]:
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[7761  158]
 [ 100 8479]]
              precision    recall  f1-score   support

           0       0.99      0.98      0.98      7919
           1       0.98      0.99      0.99      8579

    accuracy                           0.98     16498
   macro avg       0.98      0.98      0.98     16498
weighted avg       0.98      0.98      0.98     16498



In [19]:

comm=np.array(["hello"])

comm_idf=tfidf.transform(comm)



In [ ]:

yp=model.predict(comm_idf)
yp




array([1])